name: corsac_middleware
version: 0.1.0-dev
description: Corsac Middleware Pipeline component
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
#homepage: https://www.example.com

environment:
    sdk: '>=1.9.0 <2.0.0'

dev_dependencies:
    test: "^0.12.4+7"
    mockito: "^0.11.0"
